version: "2.0"
services:
  worshipdata:
   image: ericmjl/worshipdata
   volumes:
     - "/worship-manager/data"

  worshipmanager:
    image: ericmjl/worship
    volumes_from:
     - worshipdata
    depends_on:
     - worshipdata
    ports:
     - 80:8080
