name: worship
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.7
- flask
- pyyaml
- pytest
- pytest-cov
- python-pptx
- mypy
- doc8
- black
- pycodestyle
- pip:
    - hanziconv
    - flask-breadcrumbs
    - pinyin
    - tinydb
    - sphinx
    - gspread
    - oauth2client
    - PyOpenSSL
