name: worship
channels:
- defaults
- conda-forge
- ericmjl
- bioconda
dependencies:
- python=3.7
- flask
- pyyaml
- pytest
- pytest-cov
- mypy
- doc8
- black
- pycodestyle
- imagemagick
- perl-image-exiftool
- python-dotenv
- boto3
- gunicorn
- poppler
- pandas
- pylint
- pip:
    - hanziconv
    - pinyin
    - tinydb
    - oauth2client
    - PyOpenSSL
    - preview-generator
    - pgcli
    - flask_sqlalchemy
