name: worship
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- flask=0.12
- pyyaml
- pytest=3.2.0
- pytest-cov=2.5.1
- python-pptx
- pip:
    - hanziconv
    - flask-breadcrumbs==0.4
    - pinyin
    - tinydb
    - sphinx==1.6.3
    - gspread
    - oauth2client
    - PyOpenSSL
