name: worship
channels:
- defaults
- conda-forge
- ericmjl
- bioconda
dependencies:
- python=3.7
- flask
- pyyaml
- pytest
- pytest-cov
- python-pptx
- mypy
- doc8
- black
- pycodestyle
- imagemagick
- perl-image-exiftool
- python-dotenv
- boto3
- gunicorn
- pip:
    - hanziconv
    - flask-breadcrumbs
    - pinyin
    - tinydb
    - sphinx
    - gspread
    - oauth2client
    - PyOpenSSL
    - preview-generator
    - google_api_python_client
